// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	pb "tgtest/proto/pb"

	mock "github.com/stretchr/testify/mock"
)

// BalanceClientRPC is an autogenerated mock type for the BalanceClientRPC type
type BalanceClientRPC struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *BalanceClientRPC) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, accountID
func (_m *BalanceClientRPC) GetBalance(ctx context.Context, accountID string) (*pb.GetBalanceResponse, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *pb.GetBalanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pb.GetBalanceResponse, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pb.GetBalanceResponse); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetBalanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBalanceClientRPC creates a new instance of BalanceClientRPC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceClientRPC(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceClientRPC {
	mock := &BalanceClientRPC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
